#!/bin/sh
. "${XDG_DATA_HOME:-$HOME/.local/share}/eddos/eddos.sh"

while read package; do
	transparent_remove "$package"
done < "${XDG_CONFIG_HOME:-$HOME/.config}/eddos/eddos-core/hooks/packages.txt"
