#!/bin/sh
init="$(ps -p 1 -o comm=)"
if [ "$init" != "systemd" ]; then
	exit 0
fi

# Enable time server synchronisation if under systemd
sudo systemctl enable systemd-timesyncd.service
sudo systemctl start systemd-timesyncd.service
